In [2]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (0.13.1)
Requirement already satisfied: pandas>=1.2 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (1.5.1)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (1.23.4)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (3.8.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: cycler>=0.10 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: packaging>=20.0 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.44.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\thekra\appdata\roaming\python\python39\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: pillow>=8 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.1.0)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.1.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.17.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\thekra\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2022.5)
Requirement already satisfied: six>=1.5 in c:\users\thekra\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 24.0 is available.
You should consider upgrading via the 'c:\Users\Thekra\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob as glob

Step.1: Read the datasets

In [27]:
#load 2019 air quality data
co_19 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2019/CO_2019.csv')
no2_19 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2019/NO2_2019.csv')
o3_19 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2019/O3_2019.csv')
pm25_19= pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2019/PM2.5_2019.csv')
pm10_19 =pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2019/PM10_2019.csv')

In [28]:
#load 2020 air quality data
co_20 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2020/CO_2020.csv')
no2_20 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2020/NO2_2020.csv')
o3_20 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2020/O3_2020.csv')
pm25_20= pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2020/PM2.5_2020.csv')
pm10_20 =pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2020/PM10_2020.csv')

In [7]:
#load 2021 air quality data
co_21 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2021/CO_2021.csv')
no2_21 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2021/NO2_2021.csv')
o3_21 = pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2021/O3_2021.csv')
pm25_21= pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2021/PM2.5_2021.csv')
pm10_21 =pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/2021/PM10_2021.csv')

In [8]:
#load covid-19 data
covid= pd.read_csv('C:/Users/Thekra/Desktop/ds_cap/DS_capstone/data/COVID-19_CA/covid19cases_deaths.csv')

Step.2: 2019 dataframes exploring and feature engineering
Along this step I have identified major data cleaning quests that needed to be resolved: missing counties, datetime data type, identift relevant features, merge

In [34]:
co_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22290 entries, 0 to 22289
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               22290 non-null  object
 1   Source                             22290 non-null  object
 2   Site ID                            22290 non-null  int64
 3   POC                                22290 non-null  int64
 4   Daily Max 8-hour CO Concentration  22290 non-null  float64
 5   UNITS                              22290 non-null  object
 6   DAILY_AQI_VALUE                    22290 non-null  int64
 7   Site Name                          22290 non-null  object
 8   DAILY_OBS_COUNT                    22290 non-null  int64
 9   PERCENT_COMPLETE                   22290 non-null  float64
 10  AQS_PARAMETER_CODE                 22290 non-null  int64
 11  AQS_PARAMETER_DESC                 22290 non-null  object
 12  CBSA_CODE                          22290 non-null  int64
 13  CBSA_NAME                          22290 non-null  object
 14  STATE_CODE                         22290 non-null  int64
 15  STATE                              22290 non-null  object
 16  COUNTY_CODE                        22290 non-null  int64
 17  COUNTY                             22290 non-null  object
 18  SITE_LATITUDE                      22290 non-null  float64
 19  SITE_LONGITUDE                     22290 non-null  float64
dtypes: float64(4), int64(8), object(8)
memory usage: 3.4+ MB

In [19]:
#explore is all 2019 datasets have the same number of counties 
print(co_19.COUNTY.nunique())
print(pm10_19.COUNTY.nunique())
print(no2_19.COUNTY.nunique())
print(pm25_19.COUNTY.nunique())
print(o3_19.COUNTY.nunique())

25
43
33
51
49

California has 58 counties. This could be interpreted as missing values or simply the air pollutant is not being recorded in all counties. Nonetheless, we need to make sure that the same number of counties is being recorded for each of the pollutant across the 3 years

In [11]:
#2020 dataframes
print(co_20.COUNTY.nunique())
print(pm10_20.COUNTY.nunique())
print(no2_20.COUNTY.nunique())
print(pm25_20.COUNTY.nunique())
print(o3_20.COUNTY.nunique())

25
43
33
51
49

In [12]:
#2021 dataframes
print(co_21.COUNTY.nunique())
print(pm10_21.COUNTY.nunique())
print(no2_21.COUNTY.nunique())
print(pm25_21.COUNTY.nunique())
print(o3_21.COUNTY.nunique())

25
42
33
49
48

Looks like we are missing readings of PM25 from 2 counties in 2021 and O3 readings from 1 county in 2021. Let's find which counties are these

In [13]:
#define a df with the counties that are missing 
missing_counties_pm25=pm25_19[~pm25_19['COUNTY'].isin(pm25_21['COUNTY'])]

In [14]:
#print out these counties
missing_counties_pm25['COUNTY'].unique()

array(['El Dorado', 'Mendocino'], dtype=object)

In [15]:
#the same for O3
missing_counties_o3=o3_19[~o3_19['COUNTY'].isin(o3_21['COUNTY'])]

In [16]:
missing_counties_o3['COUNTY'].unique()

array(['Mendocino'], dtype=object)

In [29]:
#to keep data consistent, and due to the high numebr of missing readings per county (+1000 recordings per county) it's better to drop the missing counties than to fill with NA or averages
pm25_19.drop(pm25_19.loc[pm25_19['COUNTY'].isin(['El Dorado','Mendocino'])].index, inplace=True)
pm25_20.drop(pm25_20.loc[pm25_20['COUNTY'].isin(['El Dorado','Mendocino'])].index, inplace=True)
o3_19.drop(o3_19.loc[o3_19['COUNTY'].isin(['Mendocino'])].index, inplace=True)
o3_20.drop(o3_20.loc[o3_20['COUNTY'].isin(['Mendocino'])].index, inplace=True)

In [155]:
co_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22290 entries, 0 to 22289
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               22290 non-null  object
 1   Source                             22290 non-null  object
 2   Site ID                            22290 non-null  int64
 3   POC                                22290 non-null  int64
 4   Daily Max 8-hour CO Concentration  22290 non-null  float64
 5   UNITS                              22290 non-null  object
 6   DAILY_AQI_VALUE                    22290 non-null  int64
 7   Site Name                          22290 non-null  object
 8   DAILY_OBS_COUNT                    22290 non-null  int64
 9   PERCENT_COMPLETE                   22290 non-null  float64
 10  AQS_PARAMETER_CODE                 22290 non-null  int64
 11  AQS_PARAMETER_DESC                 22290 non-null  object
 12  CBSA_CODE                          22290 non-null  int64
 13  CBSA_NAME                          22290 non-null  object
 14  STATE_CODE                         22290 non-null  int64
 15  STATE                              22290 non-null  object
 16  COUNTY_CODE                        22290 non-null  int64
 17  COUNTY                             22290 non-null  object
 18  SITE_LATITUDE                      22290 non-null  float64
 19  SITE_LONGITUDE                     22290 non-null  float64
dtypes: float64(4), int64(8), object(8)
memory usage: 3.4+ MB

In [156]:
#We notice that 'Date' is not a Datetime format
#convert 'Date' to datetime dtype. We choose this specific arrangement as opposed to
# %d/%m/%y because the data is rcorded that way originally. This is why inspection of the CSV file initially is necessary
co_19['Date']=pd.to_datetime(co_19['Date'], format = "%m/%d/%Y")
pm10_19['Date']=pd.to_datetime(pm10_19['Date'], format = "%m/%d/%Y")
pm25_19['Date']=pd.to_datetime(pm25_19['Date'], format = "%m/%d/%Y")
no2_19['Date']=pd.to_datetime(no2_19['Date'], format = "%m/%d/%Y")
o3_19['Date']=pd.to_datetime(o3_19['Date'], format = "%m/%d/%Y")

In [157]:
#Now we will groupby() date and assign that to the original dataset. 
#Rationale for grouping by date: for every day, there is around -+50 entries; one recodrding for each county
#It's best to see the big picture and just view the concenration of that pollutant over that day,
#aka instead of +2000 entries for each dataset we will get only 365 or so depending on if there are any missing dates
#grouping by date will automatically eliminates the column 'County'
co_19=co_19.groupby('Date').mean()
o3_19=o3_19.groupby('Date').mean()
no2_19=no2_19.groupby('Date').mean()
pm10_19=pm10_19.groupby('Date').mean()
pm25_19=pm25_19.groupby('Date').mean()

C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\3832656372.py:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  co_19=co_19.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\3832656372.py:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  o3_19=o3_19.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\3832656372.py:8: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  no2_19=no2_19.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\3832656372.py:9: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pm10_19=pm10_19.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\3832656372.py:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pm25_19=pm25_19.groupby('Date').mean()

In [158]:
#example of how the df looks now 
#notice that 'County' and 'Units' were gone after grouping
no2_19

,Site ID,POC,Daily Max 1-hour NO2 Concentration,DAILY_AQI_VALUE,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,CBSA_CODE,STATE_CODE,COUNTY_CODE,SITE_LATITUDE,SITE_LONGITUDE
Date,,,,,,,,,,,,
2019-01-01,6.054638e+07,1.166667,19.560417,18.093750,23.177083,96.708333,42602.0,36027.500000,6.0,54.479167,35.704739,-119.580122
2019-01-02,6.054638e+07,1.166667,29.459375,27.520833,22.843750,95.333333,42602.0,36027.500000,6.0,54.479167,35.704739,-119.580122
2019-01-03,6.054668e+07,1.163265,30.051020,28.030612,22.959184,95.795918,42602.0,36023.673469,6.0,54.510204,35.686228,-119.569303
2019-01-04,6.054689e+07,1.163265,32.317347,30.214286,23.000000,95.979592,42602.0,36040.000000,6.0,54.530612,35.675181,-119.564776
2019-01-05,6.054689e+07,1.163265,24.112245,22.438776,23.051020,96.204082,42602.0,36040.000000,6.0,54.530612,35.675181,-119.564776

In [159]:
#for this dataset, 365 data entries (as expected) where previously it was 34,515 
no2_19.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 365 entries, 2019-01-01 to 2019-12-31
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Site ID                             365 non-null    float64
 1   POC                                 365 non-null    float64
 2   Daily Max 1-hour NO2 Concentration  365 non-null    float64
 3   DAILY_AQI_VALUE                     365 non-null    float64
 4   DAILY_OBS_COUNT                     365 non-null    float64
 5   PERCENT_COMPLETE                    365 non-null    float64
 6   AQS_PARAMETER_CODE                  365 non-null    float64
 7   CBSA_CODE                           365 non-null    float64
 8   STATE_CODE                          365 non-null    float64
 9   COUNTY_CODE                         365 non-null    float64
 10  SITE_LATITUDE                       365 non-null    float64
 11  SITE_LONGITUDE                      365 non-null    float64
dtypes: float64(12)
memory usage: 37.1 KB

In [160]:
#eliminated the following columns because of their irrelevance: Site ID, POC, Dails AQI, Daily OBS, AQSParamerter code, CBSA_code. StateCode, CountyCoe, Site latitude, site longitude
co_19.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
pm25_19.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
pm10_19.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
o3_19.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
no2_19.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)

In [161]:
o3_19.head()

            Daily Max 8-hour Ozone Concentration  PERCENT_COMPLETE
Date
2019-01-01                              0.033000         99.734177
2019-01-02                              0.030066         99.523179
2019-01-03                              0.028192         99.384615
2019-01-04                              0.028737         99.884615
2019-01-05                              0.031823         99.810127

In [162]:
#Are we misisng any dates?
print(co_19.shape)
print(no2_19.shape)
print(o3_19.shape)
print(pm10_19.shape)
print(pm25_19.shape)

(365, 2)
(365, 2)
(364, 2)
(365, 2)
(365, 2)

In [163]:
#find which day is missing in O3_19 
pd.date_range(start = '2019-01-01', end = '2019-12-31').difference(o3_19.index)

DatetimeIndex(['2019-12-31'], dtype='datetime64[ns]', freq=None)

In [164]:
#confirm the information above
o3_19.tail()

            Daily Max 8-hour Ozone Concentration  PERCENT_COMPLETE
Date
2019-12-26                              0.031275         99.607843
2019-12-27                              0.029230         99.447368
2019-12-28                              0.029285         99.506329
2019-12-29                              0.028924         99.582278
2019-12-30                              0.028506         99.582278

In [165]:
#Are we missing any data points at all?
print(co_19.isna().any())
print(o3_19.isna().any())
print(no2_19.isna().any())
print(pm10_19.isna().any())
print(pm25_19.isna().any())

Daily Max 8-hour CO Concentration    False
PERCENT_COMPLETE                     False
dtype: bool
Daily Max 8-hour Ozone Concentration    False
PERCENT_COMPLETE                        False
dtype: bool
Daily Max 1-hour NO2 Concentration    False
PERCENT_COMPLETE                      False
dtype: bool
Daily Mean PM10 Concentration    False
PERCENT_COMPLETE                 False
dtype: bool
Daily Mean PM2.5 Concentration    False
PERCENT_COMPLETE                  False
dtype: bool

In [167]:
#rename columns
co_19.rename(columns={'Site ID':'site_id', 'Daily Max 8-hour CO Concentration':'daily_max_co','PERCENT_COMPLETE':'percent_complete_co'}, inplace=True)
no2_19.rename(columns={'Site ID':'site_id','Daily Max 1-hour NO2 Concentration':'daily_max_no2', 'PERCENT_COMPLETE':'percent_complete_no2'}, inplace=True)
o3_19.rename(columns={'Site ID':'site_id','Daily Max 8-hour Ozone Concentration':'daily_max_o3','PERCENT_COMPLETE':'percent_complete_o3'}, inplace=True)
pm10_19.rename(columns={'Site ID':'site_id','Daily Mean PM10 Concentration':'daily_mean_pm10','PERCENT_COMPLETE':'percent_complete_pm10'}, inplace=True)
pm25_19.rename(columns={'Site ID':'site_id','Daily Mean PM2.5 Concentration':'daily_mean_pm2.5','PERCENT_COMPLETE':'percent_complete_pm25'}, inplace=True)

Before we merge let's explore something fun and interesting to hone our coding skills. 
According to the dictionary, a minimum percent complete for any pollutant on any given day of 75% is required. 
Lets explore if any percent_complete is below 75?

In [170]:
co_19.dtypes

daily_max_co        float64
percent_complete    float64
dtype: object

In [172]:
##It is not possible to query the column percent_complete if it is object dtype
#convert to dtype float as opposed to int because the column contains decimal numbers
co_19.astype('float64')
no2_19.astype('float64')
o3_19.astype('float64')
pm10_19.astype('float64')
pm25_19.astype('float64')

            daily_max_co  percent_complete
Date
2019-01-01      0.477049         75.868852
2019-01-02      0.685246         95.786885
2019-01-03      0.766129         96.580645
2019-01-04      0.830645         98.129032
2019-01-05      0.840323         99.193548
...                  ...               ...
2019-12-27      0.608333         96.550000
2019-12-28      0.693333         98.683333
2019-12-29      0.788333         98.966667
2019-12-30      0.698333         99.033333
2019-12-31      0.648333         96.066667

[365 rows x 2 columns]

In [173]:
#find any % complete below 75
print(co_19['percent_complete'] < 75.0).any()
print(no2_19['percent_complete'] < 75.0).any()
print(o3_19['percent_complete'] < 75.0).any()
print(pm10_19['percent_complete'] < 75.0).any()
print(pm25_19['percent_complete'] < 75.0).any()

False

In [176]:
#After confirming the percent_complete, we can drop the column
co_19.drop(['percent_complete'], axis=1,inplace=True)
no2_19.drop(['percent_complete'], axis=1, inplace=True)
o3_19.drop(['percent_complete'], axis=1, inplace=True)
pm10_19.drop(['percent_complete'], axis=1, inplace=True)
pm25_19.drop(['percent_complete'], axis=1, inplace=True)

In [178]:
co_19

            daily_max_co
Date
2019-01-01      0.477049
2019-01-02      0.685246
2019-01-03      0.766129
2019-01-04      0.830645
2019-01-05      0.840323
...                  ...
2019-12-27      0.608333
2019-12-28      0.693333
2019-12-29      0.788333
2019-12-30      0.698333
2019-12-31      0.648333

[365 rows x 1 columns]

Step.3: Merge 2019 dataframes

In [179]:
from functools import reduce

In [180]:
df2019=[co_19,o3_19,no2_19,pm10_19,pm25_19]

In [181]:
#how='outer': This results in the union of keys from both frames. All rows from both DataFrames will be included.
#filling in NaNs where necessary if a key is present in one frame but not in the other
air2019 = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],
                                            how='outer'), df2019)
print(air2019)

            daily_max_co  daily_max_o3  daily_max_no2  daily_mean_pm10  \
Date
2019-01-01      0.477049      0.033000      19.560417        16.166667
2019-01-02      0.685246      0.030066      29.459375        17.734940
2019-01-03      0.766129      0.028192      30.051020        24.357664
2019-01-04      0.830645      0.028737      32.317347        23.626506
2019-01-05      0.840323      0.031823      24.112245        19.404762
...                  ...           ...            ...              ...
2019-12-27      0.608333      0.029230      24.465556        10.439024
2019-12-28      0.693333      0.029285      23.453846        15.768293
2019-12-29      0.788333      0.028924      20.415217        15.425373
2019-12-30      0.698333      0.028506      23.014130        11.462500
2019-12-31      0.648333           NaN      23.470330        14.975610

            daily_mean_pm2.5
Date
2019-01-01          9.606452
2019-01-02         12.747414
2019-01-03         16.041667
2019-01-04         18.258065
2019-01-05         11.968293
...                      ...
2019-12-27          7.513821
2019-12-28         12.344715
2019-12-29         12.076020
2019-12-30          8.441667
2019-12-31         11.286508

[365 rows x 5 columns]

In [182]:
air2019

,daily_max_co,daily_max_o3,daily_max_no2,daily_mean_pm10,daily_mean_pm2.5
Date,,,,,
2019-01-01,0.477049,0.033000,19.560417,16.166667,9.606452
2019-01-02,0.685246,0.030066,29.459375,17.734940,12.747414
2019-01-03,0.766129,0.028192,30.051020,24.357664,16.041667
2019-01-04,0.830645,0.028737,32.317347,23.626506,18.258065
2019-01-05,0.840323,0.031823,24.112245,19.404762,11.968293
...,...,...,...,...,...
2019-12-27,0.608333,0.029230,24.465556,10.439024,7.513821
2019-12-28,0.693333,0.029285,23.453846,15.768293,12.344715
2019-12-29,0.788333,0.028924,20.415217,15.425373,12.076020
2019-12-30,0.698333,0.028506,23.014130,11.462500,8.441667
2019-12-31,0.648333,NaN,23.470330,14.975610,11.286508

2020 Datasets

In [183]:
co_20

,Date,Source,Site ID,POC,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2020,AQS,60010009,1,0.7,ppm,8,Oakland,18,75.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
1,01/02/2020,AQS,60010009,1,0.7,ppm,8,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
2,01/03/2020,AQS,60010009,1,0.9,ppm,10,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
3,01/04/2020,AQS,60010009,1,0.8,ppm,9,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
4,01/05/2020,AQS,60010009,1,0.7,ppm,8,Oakland,24,100.0,42101,Carbon monoxide,41860,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.743065,-122.169935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22130,12/27/2020,AQS,60990005,3,1.1,ppm,13,Modesto-14th Street,24,100.0,42101,Carbon monoxide,33700,"Modesto, CA",6,California,99,Stanislaus,37.642165,-120.994212
22131,12/28/2020,AQS,60990005,3,1.1,ppm,13,Modesto-14th Street,24,100.0,42101,Carbon monoxide,33700,"Modesto, CA",6,California,99,Stanislaus,37.642165,-120.994212
22132,12/29/2020,AQS,60990005,3,1.6,ppm,18,Modesto-14th Street,24,100.0,42101,Carbon monoxide,33700,"Modesto, CA",6,California,99,Stanislaus,37.642165,-120.994212
22133,12/30/2020,AQS,60990005,3,1.7,ppm,19,Modesto-14th Street,24,100.0,42101,Carbon monoxide,33700,"Modesto, CA",6,California,99,Stanislaus,37.642165,-120.994212
22134,12/31/2020,AQS,60990005,3,1.1,ppm,13,Modesto-14th Street,24,100.0,42101,Carbon monoxide,33700,"Modesto, CA",6,California,99,Stanislaus,37.642165,-120.994212

In [184]:
#Same number of counties
print(co_20.COUNTY.nunique())
print(pm10_20.COUNTY.nunique())
print(no2_20.COUNTY.nunique())
print(pm25_20.COUNTY.nunique())
print(o3_20.COUNTY.nunique())

25
43
33
51
49

In [185]:
#explore data type
co_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22135 entries, 0 to 22134
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               22135 non-null  object
 1   Source                             22135 non-null  object
 2   Site ID                            22135 non-null  int64
 3   POC                                22135 non-null  int64
 4   Daily Max 8-hour CO Concentration  22135 non-null  float64
 5   UNITS                              22135 non-null  object
 6   DAILY_AQI_VALUE                    22135 non-null  int64
 7   Site Name                          22135 non-null  object
 8   DAILY_OBS_COUNT                    22135 non-null  int64
 9   PERCENT_COMPLETE                   22135 non-null  float64
 10  AQS_PARAMETER_CODE                 22135 non-null  int64
 11  AQS_PARAMETER_DESC                 22135 non-null  object
 12  CBSA_CODE                          22135 non-null  int64
 13  CBSA_NAME                          22135 non-null  object
 14  STATE_CODE                         22135 non-null  int64
 15  STATE                              22135 non-null  object
 16  COUNTY_CODE                        22135 non-null  int64
 17  COUNTY                             22135 non-null  object
 18  SITE_LATITUDE                      22135 non-null  float64
 19  SITE_LONGITUDE                     22135 non-null  float64
dtypes: float64(4), int64(8), object(8)
memory usage: 3.4+ MB

In [186]:
#We notice that 'Date' is not a Datetime format
#convert 'Date' to datetime dtype. We choose this specific arrangement as opposed to
# %d/%m/%y because the data is rcorded that way originally. This is why first inspection of the CSV file is necessary
co_20['Date']=pd.to_datetime(co_20['Date'], format = "%m/%d/%Y")
pm10_20['Date']=pd.to_datetime(pm10_20['Date'], format = "%m/%d/%Y")
pm25_20['Date']=pd.to_datetime(pm25_20['Date'], format = "%m/%d/%Y")
no2_20['Date']=pd.to_datetime(no2_20['Date'], format = "%m/%d/%Y")
o3_20['Date']=pd.to_datetime(o3_20['Date'], format = "%m/%d/%Y")

In [187]:
co_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22135 entries, 0 to 22134
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               22135 non-null  datetime64[ns]
 1   Source                             22135 non-null  object
 2   Site ID                            22135 non-null  int64
 3   POC                                22135 non-null  int64
 4   Daily Max 8-hour CO Concentration  22135 non-null  float64
 5   UNITS                              22135 non-null  object
 6   DAILY_AQI_VALUE                    22135 non-null  int64
 7   Site Name                          22135 non-null  object
 8   DAILY_OBS_COUNT                    22135 non-null  int64
 9   PERCENT_COMPLETE                   22135 non-null  float64
 10  AQS_PARAMETER_CODE                 22135 non-null  int64
 11  AQS_PARAMETER_DESC                 22135 non-null  object
 12  CBSA_CODE                          22135 non-null  int64
 13  CBSA_NAME                          22135 non-null  object
 14  STATE_CODE                         22135 non-null  int64
 15  STATE                              22135 non-null  object
 16  COUNTY_CODE                        22135 non-null  int64
 17  COUNTY                             22135 non-null  object
 18  SITE_LATITUDE                      22135 non-null  float64
 19  SITE_LONGITUDE                     22135 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(8), object(7)
memory usage: 3.4+ MB

In [188]:
co_20=co_20.groupby('Date').mean()
o3_20=o3_20.groupby('Date').mean()
no2_20=no2_20.groupby('Date').mean()
pm10_20=pm10_20.groupby('Date').mean()
pm25_20=pm25_20.groupby('Date').mean()

C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\2571562249.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  co_20=co_20.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\2571562249.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  o3_20=o3_20.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\2571562249.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  no2_20=no2_20.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\2571562249.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pm10_20=pm10_20.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\2571562249.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pm25_20=pm25_20.groupby('Date').mean()

In [189]:
co_20.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
pm25_20.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
pm10_20.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
o3_20.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
no2_20.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)

In [190]:
no2_20

            Daily Max 1-hour NO2 Concentration  PERCENT_COMPLETE
Date
2020-01-01                           19.377895         96.968421
2020-01-02                           24.768085         96.319149
2020-01-03                           28.981915         96.446809
2020-01-04                           24.519149         96.595745
2020-01-05                           20.793684         96.452632
...                                        ...               ...
2020-12-27                           17.320408         96.397959
2020-12-28                           17.998958         96.125000
2020-12-29                           24.556701         95.958763
2020-12-30                           26.660825         95.804124
2020-12-31                           22.574227         96.443299

[366 rows x 2 columns]

In [191]:
#Nice. Now, are we misisng any dates?
print(co_20.shape)
print(no2_20.shape)
print(o3_20.shape)
print(pm10_20.shape)
print(pm25_20.shape)

(366, 2)
(366, 2)
(365, 2)
(366, 2)
(366, 2)

In [192]:
#looks like we have extra dates! we will use daterange and it is preprogrammed to have exactly 365 days
#so whatever more rows there is a possibility that these are duplicates. Let's find out:

In [193]:
#looks like there are 365 days and are unique. Mey be duplicates?
print(pd.date_range(start = '2019-01-01', end = '2019-12-31').difference(co_20.index))
print(pd.date_range(start = '2019-01-01', end = '2019-12-31').difference(o3_20.index))
print(pd.date_range(start = '2019-01-01', end = '2019-12-31').difference(no2_20.index))
print(pd.date_range(start = '2019-01-01', end = '2019-12-31').difference(pm10_20.index))
print(pd.date_range(start = '2019-01-01', end = '2019-12-31').difference(pm25_20.index))

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq=None)
DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq=None)
DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq=None)
DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq=None)
DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq=None)

In [194]:
#days are complete so may be duplicated rows
print(co_20.duplicated().value_counts())
print(no2_20.duplicated().value_counts())
print(o3_20.duplicated().value_counts())
print(pm10_20.duplicated().value_counts())
print(pm25_20.duplicated().value_counts())

False    365
True       1
dtype: int64
False    366
dtype: int64
False    364
True       1
dtype: int64
False    364
True       2
dtype: int64
False    366
dtype: int64

In [195]:
duplicated=pd.DataFrame(pm10_20.duplicated())
print(duplicated)

                0
Date
2020-01-01  False
2020-01-02  False
2020-01-03  False
2020-01-04  False
2020-01-05  False
...           ...
2020-12-27  False
2020-12-28  False
2020-12-29  False
2020-12-30  False
2020-12-31  False

[366 rows x 1 columns]

In [196]:
pm10_20[pm10_20.duplicated()]

            Daily Mean PM10 Concentration  PERCENT_COMPLETE
Date
2020-01-21                      14.000000             100.0
2020-08-05                      29.925926             100.0

In [197]:
o3_20[o3_20.duplicated()]

            Daily Max 8-hour Ozone Concentration  PERCENT_COMPLETE
Date
2020-05-03                              0.045295         99.746988

In [198]:
co_20[co_20.duplicated()]

            Daily Max 8-hour CO Concentration  PERCENT_COMPLETE
Date
2020-08-10                           0.303226         97.790323

In [205]:
print(co_20.isna().any())
print(o3_20.isna().any())
print(no2_20.isna().any())
print(pm10_20.isna().any())
print(pm25_20.isna().any())

Daily Max 8-hour CO Concentration    False
PERCENT_COMPLETE                     False
dtype: bool
Daily Max 8-hour Ozone Concentration    False
PERCENT_COMPLETE                        False
dtype: bool
Daily Max 1-hour NO2 Concentration    False
PERCENT_COMPLETE                      False
dtype: bool
Daily Mean PM10 Concentration    False
PERCENT_COMPLETE                 False
dtype: bool
Daily Mean PM2.5 Concentration    False
PERCENT_COMPLETE                  False
dtype: bool

In [215]:
co_20

            Daily Max 8-hour CO Concentration
Date
2020-01-01                           0.609836
2020-01-02                           0.650820
2020-01-03                           0.801639
2020-01-04                           0.831148
2020-01-05                           0.732787
...                                       ...
2020-12-27                           0.558333
2020-12-28                           0.421667
2020-12-29                           0.613115
2020-12-30                           0.711475
2020-12-31                           0.693220

[366 rows x 1 columns]

In [227]:
co_20.rename(columns={'Site ID':'site_id','Daily Max 8-hour CO Concentration':'daily_max_co', 'PERCENT_COMPLETE':'percent_complete'}, inplace=True)
no2_20.rename(columns={'Site ID':'site_id','Daily Max 1-hour NO2 Concentration':'daily_max_no2', 'PERCENT_COMPLETE':'percent_complete'}, inplace=True)
o3_20.rename(columns={'Site ID':'site_id','Daily Max 8-hour Ozone Concentration':'daily_max_o3','PERCENT_COMPLETE':'percent_complete'}, inplace=True)
pm10_20.rename(columns={'Site ID':'site_id','Daily Mean PM10 Concentration':'daily_mean_pm10','PERCENT_COMPLETE':'percent_complete'}, inplace=True)
pm25_20.rename(columns={'Site ID':'site_id','Daily Mean PM2.5 Concentration':'daily_mean_pm2.5','PERCENT_COMPLETE':'percent_complete'}, inplace=True)

In [228]:
print(co_20.columns)

Index(['daily_max_co'], dtype='object')

In [229]:
co_20.drop(['percent_complete'], axis=1, inplace=True)
no2_20.drop(['percent_complete'], axis=1, inplace=True)
o3_20.drop(['percent_complete'], axis=1, inplace=True)
pm10_20.drop(['percent_complete'], axis=1, inplace=True)
pm25_20.drop(['percent_complete'], axis=1, inplace=True)

KeyError: "['percent_complete'] not found in axis"

In [230]:
df2020=[co_20,o3_20,no2_20,pm10_20,pm25_20]
air2020 = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],how='outer'), df2020)
air2020

,daily_max_co,daily_max_o3,daily_max_no2,daily_mean_pm10,daily_mean_pm2.5
Date,,,,,
2020-01-01,0.609836,0.030753,19.377895,17.615385,14.747429
2020-01-02,0.650820,0.028703,24.768085,16.880952,11.920155
2020-01-03,0.801639,0.027613,28.981915,19.894118,14.472222
2020-01-04,0.831148,0.031654,24.519149,19.930556,13.150725
2020-01-05,0.732787,0.033019,20.793684,13.023810,10.455725
...,...,...,...,...,...
2020-12-27,0.558333,0.030357,17.320408,13.482353,8.468889
2020-12-28,0.421667,0.033258,17.998958,8.625000,5.737594
2020-12-29,0.613115,0.028858,24.556701,10.465649,7.941799
2020-12-30,0.711475,0.029201,26.660825,14.488095,10.451095
2020-12-31,0.693220,NaN,22.574227,16.132530,11.587681

2021 Datasets

In [232]:
#different numbers of counties
print(co_21.COUNTY.nunique())
print(pm10_21.COUNTY.nunique())
print(no2_21.COUNTY.nunique())
print(pm25_21.COUNTY.nunique())
print(o3_21.COUNTY.nunique())

25
42
33
49
48

In [233]:
#explore data type
co_21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16968 entries, 0 to 16967
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               16968 non-null  object
 1   Source                             16968 non-null  object
 2   Site ID                            16968 non-null  int64
 3   POC                                16968 non-null  int64
 4   Daily Max 8-hour CO Concentration  16968 non-null  float64
 5   UNITS                              16968 non-null  object
 6   DAILY_AQI_VALUE                    16968 non-null  int64
 7   Site Name                          16968 non-null  object
 8   DAILY_OBS_COUNT                    16968 non-null  int64
 9   PERCENT_COMPLETE                   16968 non-null  float64
 10  AQS_PARAMETER_CODE                 16968 non-null  int64
 11  AQS_PARAMETER_DESC                 16968 non-null  object
 12  CBSA_CODE                          16968 non-null  int64
 13  CBSA_NAME                          16968 non-null  object
 14  STATE_CODE                         16968 non-null  int64
 15  STATE                              16968 non-null  object
 16  COUNTY_CODE                        16968 non-null  int64
 17  COUNTY                             16968 non-null  object
 18  SITE_LATITUDE                      16968 non-null  float64
 19  SITE_LONGITUDE                     16968 non-null  float64
dtypes: float64(4), int64(8), object(8)
memory usage: 2.6+ MB

In [234]:
co_21['Date']=pd.to_datetime(co_21['Date'], format = "%m/%d/%Y")
pm10_21['Date']=pd.to_datetime(pm10_21['Date'], format = "%m/%d/%Y")
pm25_21['Date']=pd.to_datetime(pm25_21['Date'], format = "%m/%d/%Y")
no2_21['Date']=pd.to_datetime(no2_21['Date'], format = "%m/%d/%Y")
o3_21['Date']=pd.to_datetime(o3_21['Date'], format = "%m/%d/%Y")

In [235]:
co_21=co_21.groupby('Date').mean()
o3_21=o3_21.groupby('Date').mean()
no2_21=no2_21.groupby('Date').mean()
pm10_21=pm10_21.groupby('Date').mean()
pm25_21=pm25_21.groupby('Date').mean()

C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\28008911.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  co_21=co_21.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\28008911.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  o3_21=o3_21.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\28008911.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  no2_21=no2_21.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\28008911.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pm10_21=pm10_21.groupby('Date').mean()
C:\Users\Thekra\AppData\Local\Temp\ipykernel_5828\28008911.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pm25_21=pm25_21.groupby('Date').mean()

In [237]:
co_21.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
pm25_21.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
pm10_21.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
o3_21.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)
no2_21.drop(['Site ID','POC','CBSA_CODE','DAILY_AQI_VALUE','DAILY_OBS_COUNT',
             'AQS_PARAMETER_CODE','STATE_CODE','COUNTY_CODE','SITE_LATITUDE','SITE_LONGITUDE'], axis=1, inplace=True)

--------------------------------------------------------------------------------------------------

In [ ]:
#df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
#df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

#result = pd.concat([df1, df2])
#result = pd.concat([df1, df2], axis=1)
#print(result)

In [ ]:
#df1 = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3']})
#df2 = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

#result = pd.merge(df1, df2)
#print(result)

IndentationError: unexpected indent (2386845606.py, line 2)

In [ ]:
#set 'Date' as the index
co_19.set_index('Date')
o3_19.set_index('Date')
no2_19.set_index('Date')
pm10_19.set_index('Date')
pm25_19.set_index('Date')

In [ ]:
#perform groupby() on each of the 5 air quality datasets to get the daily average concentration for each county
co_19_mean= co_19.sort_index().groupby(['Date','COUNTY'])[['Daily Max 8-hour CO Concentration']].mean().round(2)
pm10_19_mean= pm10_19.sort_index().groupby(['Date','COUNTY'])[['Daily Mean PM10 Concentration']].mean().round(2)
pm25_19_mean = pm25_19.sort_index().groupby(['Date','COUNTY'])[['Daily Mean PM2.5 Concentration']].mean().round(2)
o3_19_mean = o3_19.sort_index().groupby(['Date', 'COUNTY'])[['Daily Max 8-hour Ozone Concentration']].mean().round(2)
no2_19_mean = no2_19.sort_index().groupby(['Date','COUNTY'])[['Daily Max 1-hour NO2 Concentration']].mean().round(2)

In [ ]:
#the concatenated df of 2019 datasets should have 19,345 rows (364 days * 53 counties)
air19= pd.concat([co_19_mean, pm10_19_mean, pm25_19_mean, o3_19_mean, no2_19_mean], join='outer', axis=1)
air19

In [ ]:
#find missing dates if there's any
pd.date_range(start = '2019-01-01', end = '2019-12-31').difference(air19.index)

In [ ]:
#even if some counties don't have measueemnet for a specifc pollutatnt, it should be listed and have NaN for the value of that specifc pollutant

In [ ]:
#check the number of counties in the dataset. counties are now indecies after appkying groupby()
list(air19.index)

In [ ]:
air19.index.unique(level='COUNTY').value_counts().sum()

In [ ]:
#find columns with no recodidings on a specifc day (which indicates wrong calculation)
air19[air19.isnull().all(axis=1)]

In [ ]:
air19[air19.isnull().any(axis=1)]

In [ ]:
#apply groupby() to each of the 5 air quality datasets from 2020 to get the daily average concentration for each county
co_20_mean= co_20.sort_index().groupby(['Date', 'COUNTY'])[['Daily Max 8-hour CO Concentration']].mean().round(2)
pm10_20_mean= pm10_20.sort_index().groupby(['Date', 'COUNTY'])[['Daily Mean PM10 Concentration']].mean().round(2)
pm25_20_mean = pm25_20.sort_index().groupby(['Date','COUNTY'])[['Daily Mean PM2.5 Concentration']].mean().round(2)
o3_20_mean = o3_20.sort_index().groupby(['Date','COUNTY'])[['Daily Max 8-hour Ozone Concentration']].mean().round(2)
no2_20_mean = no2_20.sort_index().groupby(['Date','COUNTY'])[['Daily Max 1-hour NO2 Concentration']].mean().round(2)

In [ ]:
#concatenate 2019 and 2020 data
air20= pd.concat([air19, co_20_mean, pm10_20_mean, pm25_20_mean, o3_20_mean, no2_20_mean], join='outer')
air20

In [ ]:
air20.reset_index(inplace=True)

In [ ]:
new_df21.info()

In [ ]:
new_df21[['Date', 'COUNTY']].duplicated().sum()

In [ ]:
#apply groupby() on each of the 5 air quality datasets from 2021 to get the daily average concentration for each county
co_21_mean= co_21.sort_index().groupby(['Date','COUNTY'])[['Daily Max 8-hour CO Concentration']].mean().round(2)
pm10_21_mean= pm10_21.sort_index().groupby(['Date','COUNTY'])[['Daily Mean PM10 Concentration']].mean().round(2)
pm25_21_mean = pm25_21.sort_index().groupby(['Date','COUNTY'])[['Daily Mean PM2.5 Concentration']].mean().round(2)
o3_21_mean = o3_21.sort_index().groupby(['Date', 'COUNTY'])[['Daily Max 8-hour Ozone Concentration']].mean().round(2)
no2_21_mean = no2_21.sort_index().groupby(['Date','COUNTY'])[['Daily Max 1-hour NO2 Concentration']].mean().round(2)

In [ ]:
co_21.sort_index().groupby(['Date','COUNTY'])[['Daily Max 8-hour CO Concentration']].mean().round(2)

In [ ]:
print(co_21_mean.shape)
print(no2_21_mean.shape)
print(o3_21_mean.shape)
print(pm10_21_mean.shape)
print(pm25_21_mean.shape)

In [ ]:
#new_df20.reset_index(inplace=True)

In [ ]:
#co_21_mean.reset_index(inplace=True)
#pm10_21_mean.reset_index(inplace=True)
#pm25_21_mean.reset_index(inplace=True)
#o3_21_mean.reset_index(inplace=True)
#no2_21_mean.reset_index(inplace=True)

In [ ]:
#the concatenated df of 2021 datasets should have 19,345 rows
air21= pd.merge([co_21_mean, pm10_21_mean, pm25_21_mean, o3_21_mean, no2_21_mean], on='Date')
air21

In [ ]:
#the concatenated df of 2021 datasets should have 18,980 rows (52 counties * 365 days)
air21= pd.concat([co_21_mean, pm10_21_mean, pm25_21_mean, o3_21_mean, no2_21_mean], join='outer', axis=1)
air21

In [ ]:
#number of counties in 2021 dataset
air21.index.unique(level='COUNTY').value_counts().sum()

In [ ]:
#check for missing dates
pd.date_range(start = '2021-01-01', end = '2021-12-31').difference(air19.index)

In [ ]:
air21.reset_index(inplace=True)

In [ ]:
#check for duplicates
air21.duplicated().value_counts()

In [ ]:
#check the unique counties in COVID-19 and air19 datasets
cov_county = list(covid.area.unique())
cov_county

In [ ]:
covid.area.unique()

In [ ]:
[x for x in covid.area.unique() if x not in air19.index]

In [ ]:
for x in covid.area.unique():
    if x not in co_19.COUNTY.unique():
        print(x)

In [ ]:
list(air21.index.values.sum())

In [ ]:
air21.index.values.tolist()

------------------------------------------------------------------------------------------------------------

In [ ]:
#concat() 2019 data
new_df= pd.concat([co_19, pm10_19, pm25_19, o3_19, no2_19], join='outer', axis=1)
new_df

In [ ]:
#concat 2019 and 2020 data
new_df20= pd.concat([new_df, co_20, pm10_20, pm25_20, o3_20, no2_20], join='outer')
new_df20

Final thoughts:
> You can search for exactly which counties are missing and dig deeper in analysis. You might create a list of all the countiyes of California then use glob() or any relevant method 
> It's important to understant why some pollutants recorded as Max while others at Mean